import type { Listing, Expansion, AlertRule } from "@shared/schema";

export const SEED_LISTINGS: Listing[] = [
  {
    id: 1,
    name: "Wolfspeed Farmers Branch Epitaxy Campus",
    broker: "LoopNet / Direct",
    status: "active",
    type: "fab",
    waferSizes: JSON.stringify(["150mm"]),
    squareFootage: 457000,
    powerCapacityMW: 14,
    state: "TX",
    city: "Farmers Branch",
    lat: 32.926,
    lng: -96.889,
    askingPrice: "Undisclosed",
    nodes: JSON.stringify(["SiC Epitaxy", "GaN", "150mm"]),
    seller: "Wolfspeed",
    listedDate: "2025-01",
    notes: "4-building campus on 26 acres. Bldg A is 162,500 sf fab. Bldg G is a 14MW data center expandable to 28MW. Post-bankruptcy disposition.",
    sourceUrl: "https://www.datacenterdynamics.com/en/news/chipmaker-wolfspeed-closes-texas-site-puts-up-for-sale/",
  },
  {
    id: 2,
    name: "Wolfspeed Durham 150mm Device Fab",
    broker: "ATREG / Direct",
    status: "active",
    type: "fab",
    waferSizes: JSON.stringify(["150mm"]),
    squareFootage: 120000,
    powerCapacityMW: 8,
    state: "NC",
    city: "Durham",
    lat: 35.994,
    lng: -78.899,
    askingPrice: "Undisclosed",
    nodes: JSON.stringify(["SiC", "GaN", "150mm Power"]),
    seller: "Wolfspeed",
    listedDate: "2025-H2",
    notes: "Shut down ahead of schedule. Full 150mm SiC device production line. Part of Wolfspeed Chapter 11 restructuring.",
    sourceUrl: "https://assets.wolfspeed.com/uploads/2026/02/Wolfspeed_Q2_2026_Earnings_Release.pdf",
  },
  {
    id: 3,
    name: "150mm Wafer Foundry – San Jose (Moov Technologies)",
    broker: "Moov Technologies",
    status: "active",
    type: "fab",
    waferSizes: JSON.stringify(["150mm", "100mm"]),
    squareFootage: 5998,
    powerCapacityMW: 1.2,
    state: "CA",
    city: "San Jose",
    lat: 37.378,
    lng: -121.929,
    askingPrice: "Contact Broker",
    nodes: JSON.stringify(["Bipolar", "BiCMOS", "MEMS", "150mm", "100mm"]),
    seller: "Wafer Foundry.co",
    listedDate: "2025",
    notes: "5,998 sf Industrial/R&D condo. Full 150mm foundry with 10k wafer/yr capacity. For sale or lease including equipment.",
    sourceUrl: "https://site.moov.co/hubfs/Moov_FabSaleBrochure_v3_English.pdf",
  },
  {
    id: 4,
    name: "ATREG 200mm/300mm Fab Portfolio",
    broker: "ATREG",
    status: "active",
    type: "cleanroom",
    waferSizes: JSON.stringify(["200mm", "300mm"]),
    squareFootage: null,
    powerCapacityMW: null,
    state: "US",
    city: "Multiple Locations",
    lat: 39.5,
    lng: -98.35,
    askingPrice: "Varies",
    nodes: JSON.stringify(["200mm", "300mm", "Cleanroom"]),
    seller: "Multiple Clients",
    listedDate: "2026-Q1",
    notes: "ATREG Q1 2026: diverse portfolio of 200mm and 300mm fabs and cleanrooms worldwide. Contact Annie Rothrock, COO.",
    sourceUrl: "https://atreg.com/newsletters/atreg-fab-disposition-newsletter-and-semi-update-q1-2026/",
  },
  {
    id: 5,
    name: "REC Silicon Butte Silane Gas Plant",
    broker: "Direct / TBD",
    status: "watch",
    type: "polysilicon",
    waferSizes: JSON.stringify([]),
    squareFootage: 280000,
    powerCapacityMW: 18,
    state: "MT",
    city: "Butte",
    lat: 46.003,
    lng: -112.535,
    askingPrice: "Undisclosed",
    nodes: JSON.stringify(["Polysilicon", "Silane Gas", "Solar-grade Si"]),
    seller: "REC Silicon",
    listedDate: "2025",
    notes: "Norwegian firm mulling sale after US-China trade war. Produces silane gas & polysilicon. Previously supplied Qcells. Strategic for US solar supply chain.",
    sourceUrl: "https://www.pv-tech.org/snarled-in-the-trade-war-rec-silicon-mulls-sale-of-us-plant/",
  },
  {
    id: 6,
    name: "Wolfspeed Mohawk Valley 200mm SiC Fab",
    broker: "Apollo Global / Direct",
    status: "watch",
    type: "fab",
    waferSizes: JSON.stringify(["200mm"]),
    squareFootage: 200000,
    powerCapacityMW: 40,
    state: "NY",
    city: "Marcy",
    lat: 43.164,
    lng: -75.245,
    askingPrice: "N/A – Restructuring",
    nodes: JSON.stringify(["SiC", "200mm", "Automotive-qualified"]),
    seller: "Wolfspeed / Apollo",
    listedDate: "2025-09",
    notes: "$1.2B joint investment with NY State. First 200mm SiC fab. Fully automated. Post-Chapter 11, Apollo acquired.",
    sourceUrl: "https://elevenflo.com/blog/wolfspeed-bankruptcy-46b-debt-restructuring",
  },
  {
    id: 7,
    name: "Marcy Nanocenter Greenfield Site",
    broker: "ATREG / SUNY Poly",
    status: "active",
    type: "r_and_d",
    waferSizes: JSON.stringify(["200mm", "300mm"]),
    squareFootage: 500000,
    powerCapacityMW: 50,
    state: "NY",
    city: "Marcy",
    lat: 43.165,
    lng: -75.246,
    askingPrice: "Incentives Available",
    nodes: JSON.stringify(["Greenfield", "Shovel-ready"]),
    seller: "NY State / SUNY",
    listedDate: "2025-Q1",
    notes: "Most shovel-ready greenfield site in the US per ATREG Q1 2025. Available to house semiconductor or advanced technology manufacturers.",
    sourceUrl: "https://atreg.com/newsletters/atreg-fab-disposition-newsletter-and-semi-update-q1-2025/",
  },
  {
    id: 8,
    name: "Hanwha Polysilicon Facility – US (Exiting)",
    broker: "Direct",
    status: "watch",
    type: "polysilicon",
    waferSizes: JSON.stringify([]),
    squareFootage: 150000,
    powerCapacityMW: 12,
    state: "GA",
    city: "Cartersville",
    lat: 34.165,
    lng: -84.799,
    askingPrice: "TBD",
    nodes: JSON.stringify(["Polysilicon", "Solar-grade Si"]),
    seller: "Hanwha Solutions",
    listedDate: "2025-01",
    notes: "Hanwha exiting US polysilicon manufacturing Jan 2025. Related to Qcells Georgia solar supply chain restructuring.",
    sourceUrl: "https://www.kedglobal.com/energy/newsView/ked202501030006",
  },
  {
    id: 9,
    name: "ATREG 200mm Compound Semi Fab – USA",
    broker: "ATREG",
    status: "active",
    type: "compound_semi",
    waferSizes: JSON.stringify(["200mm"]),
    squareFootage: 85000,
    powerCapacityMW: 6,
    state: "US",
    city: "Undisclosed",
    lat: 35.5,
    lng: -90.0,
    askingPrice: "Undisclosed",
    nodes: JSON.stringify(["Compound Semi", "200mm"]),
    seller: "Undisclosed",
    listedDate: "2026-Q1",
    notes: "ATREG retained to facilitate divestment of US-based compound semiconductor-capable fab. Immediate access to operational capability.",
    sourceUrl: "https://atreg.com/newsletters/",
  },
];

export const SEED_EXPANSIONS: Expansion[] = [
  {
    id: 1,
    name: "TSMC Arizona Gigafab Complex",
    company: "TSMC",
    state: "AZ",
    city: "Phoenix",
    lat: 33.677,
    lng: -112.108,
    type: "logic",
    investmentBillions: 165,
    waferSize: "300mm",
    completionYear: 2030,
    status: "under_construction",
    notes: "12-fab long-term cluster. Fab 1 (N4P) at 88-92% yield. $165B committed. AP1/AP2 advanced packaging 2026.",
    sourceUrl: "https://business.times-online.com/times-online/article/tokenring-2026-1-28-silicon-sovereignty-tsmcs-165-billion-arizona-gigafab-redefines-the-ai-global-order",
  },
  {
    id: 2,
    name: "Intel Fab 52/62 – Chandler",
    company: "Intel",
    state: "AZ",
    city: "Chandler",
    lat: 33.302,
    lng: -111.841,
    type: "logic",
    investmentBillions: 20,
    waferSize: "300mm",
    completionYear: 2027,
    status: "under_construction",
    notes: "Intel 18A process. $20B AZ investment.",
    sourceUrl: "https://www.intel.com",
  },
  {
    id: 3,
    name: "Micron DRAM Fab – Boise",
    company: "Micron Technology",
    state: "ID",
    city: "Boise",
    lat: 43.615,
    lng: -116.202,
    type: "memory",
    investmentBillions: 15,
    waferSize: "300mm",
    completionYear: 2030,
    status: "under_construction",
    notes: "CHIPS Act supported. Idaho semiconductor cluster anchor. Part of $50B+ national expansion.",
    sourceUrl: "https://www.industrialinfo.com",
  },
  {
    id: 4,
    name: "Samsung Taylor Fab",
    company: "Samsung",
    state: "TX",
    city: "Taylor",
    lat: 30.571,
    lng: -97.409,
    type: "logic",
    investmentBillions: 17,
    waferSize: "300mm",
    completionYear: 2026,
    status: "under_construction",
    notes: "4nm and below. CHIPS Act $6.4B grant recipient. Taylor, TX mega-fab.",
    sourceUrl: "https://semiconductor.samsung.com",
  },
  {
    id: 5,
    name: "Texas Instruments Richardson Fab",
    company: "Texas Instruments",
    state: "TX",
    city: "Richardson",
    lat: 32.948,
    lng: -96.729,
    type: "compound_semi",
    investmentBillions: 3.5,
    waferSize: "300mm",
    completionYear: 2026,
    status: "under_construction",
    notes: "300mm analog/mixed-signal. Part of TI $30B+ US capacity expansion.",
    sourceUrl: "https://www.ti.com",
  },
  {
    id: 6,
    name: "Wolfspeed Siler City Materials Factory",
    company: "Wolfspeed / Apollo",
    state: "NC",
    city: "Siler City",
    lat: 35.724,
    lng: -79.462,
    type: "sic",
    investmentBillions: 1.5,
    waferSize: "200mm",
    completionYear: 2025,
    status: "operational",
    notes: "World's largest 200mm SiC materials factory. 2M sf complex. Operational June 2024.",
    sourceUrl: "https://elevenflo.com/blog/wolfspeed-bankruptcy-46b-debt-restructuring",
  },
  {
    id: 7,
    name: "Bosch Roseville SiC Fab (ex-TSI)",
    company: "Bosch",
    state: "CA",
    city: "Roseville",
    lat: 38.752,
    lng: -121.288,
    type: "sic",
    investmentBillions: 1.5,
    waferSize: "200mm",
    completionYear: 2026,
    status: "under_construction",
    notes: "Acquired from TSI via ATREG. Retooling for 200mm SiC starting 2026.",
    sourceUrl: "https://www.businesswire.com/news/home/20230426005913",
  },
  {
    id: 8,
    name: "TOYO US Polysilicon Supply Site",
    company: "TOYO / US Partner",
    state: "TX",
    city: "TBD",
    lat: 31.0,
    lng: -99.0,
    type: "polysilicon",
    investmentBillions: 0.5,
    waferSize: null,
    completionYear: 2027,
    status: "planned",
    notes: "TOYO secured strategic US polysilicon supply partnership Jan 2026. Solar-grade silicon.",
    sourceUrl: "https://www.nasdaq.com/press-release/toyo-secures-strategic-polysilicon-supply-us-polysilicon-manufacturer-2026-01-07",
  },
  {
    id: 9,
    name: "Micron Idaho – Clay Township Expansion",
    company: "Micron Technology",
    state: "ID",
    city: "Clay Township",
    lat: 43.5,
    lng: -116.0,
    type: "memory",
    investmentBillions: 12,
    waferSize: "300mm",
    completionYear: 2028,
    status: "under_construction",
    notes: "Part of $27B Idaho semiconductor construction boom. Summer 2026 expected completion for initial phase.",
    sourceUrl: "https://www.industrialinfo.com/news/article/semiconductors-propel-idaho-to-27-billion-worth-of-under-construction-projects--342065",
  },
];

export const SEED_ALERT_RULES: AlertRule[] = [
  {
    id: 1,
    label: "Large 200mm+ Fab — Southwest",
    minSqft: 50000,
    maxSqft: null,
    waferSize: "200mm",
    types: JSON.stringify(["fab", "cleanroom"]),
    states: JSON.stringify(["AZ", "TX", "NM", "NV", "CA"]),
    minPowerMW: 5,
    active: 1,
    createdAt: "2026-06-01T00:00:00Z",
  },
  {
    id: 2,
    label: "Polysilicon / Solar-Si Disposition — Any State",
    minSqft: null,
    maxSqft: null,
    waferSize: null,
    types: JSON.stringify(["polysilicon"]),
    states: JSON.stringify([]),
    minPowerMW: null,
    active: 1,
    createdAt: "2026-06-15T00:00:00Z",
  },
  {
    id: 3,
    label: "Any Fab — Idaho / Texas Cluster States",
    minSqft: null,
    maxSqft: null,
    waferSize: null,
    types: JSON.stringify(["fab", "epitaxy", "compound_semi"]),
    states: JSON.stringify(["ID", "TX"]),
    minPowerMW: null,
    active: 1,
    createdAt: "2026-06-20T00:00:00Z",
  },
];
